### ISSUE TITLE
Grid column headers

### ISSUE THREAD

**Issue by znarkd** [bvaughn/react-virtualized-v10#9]
Perhaps this new version would include column headers for the Grid control.  Use rowIndex = -1 for the header row.   On each render of the Grid, rowIndex -1 would be the first row called for.

**Comment by bvaughn** [comment]
Hi @znarkd 👋

This repo is a temporary one for me to work on the rewrite idea. I only enabled GH issues yesterday for me to add a couple of TODO notes for myself, but I don't really want to be taking requests yet at this point in the project. 😄 I hope you understand!
